//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjSurveyPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryMst
    {
        public CategoryMst()
        {
            this.HelpingQues = new HashSet<HelpingQue>();
            this.ReviewAns = new HashSet<ReviewAn>();
            this.ReviewQues = new HashSet<ReviewQue>();
            this.SurveyAns = new HashSet<SurveyAn>();
            this.SurveyQues = new HashSet<SurveyQue>();
        }
    
        public byte CategoryID { get; set; }
        public string CategoryDisc { get; set; }
    
        public virtual ICollection<HelpingQue> HelpingQues { get; set; }
        public virtual ICollection<ReviewAn> ReviewAns { get; set; }
        public virtual ICollection<ReviewQue> ReviewQues { get; set; }
        public virtual ICollection<SurveyAn> SurveyAns { get; set; }
        public virtual ICollection<SurveyQue> SurveyQues { get; set; }
    }
}
