//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjSurveyPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class CityMst
    {
        public CityMst()
        {
            this.UserMsts = new HashSet<UserMst>();
        }
    
        public byte StateID { get; set; }
        public byte CityID { get; set; }
        public string CityName { get; set; }
    
        public virtual StateMst StateMst { get; set; }
        public virtual ICollection<UserMst> UserMsts { get; set; }
    }
}
