//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjSurveyPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientMst
    {
        public ClientMst()
        {
            this.ProductMsts = new HashSet<ProductMst>();
            this.SurveyMsts = new HashSet<SurveyMst>();
            this.PurchasePackages = new HashSet<PurchasePackage>();
        }
    
        public short ClientID { get; set; }
        public string CompName { get; set; }
        public string CompAddress { get; set; }
        public string OwnerName { get; set; }
        public string CompanyLogo { get; set; }
        public string ContactNo { get; set; }
        public string MobileNo { get; set; }
        public string GSTNo { get; set; }
        public string WebsiteName { get; set; }
        public string EmailID { get; set; }
        public byte[] Passwd { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> ActiveLeaveDt { get; set; }
        public Nullable<System.DateTime> LastLoginDt { get; set; }
        public Nullable<byte> ApprovedEmpID { get; set; }
        public System.DateTime JoiningDate { get; set; }
    
        public virtual EmployeeMst EmployeeMst { get; set; }
        public virtual ICollection<ProductMst> ProductMsts { get; set; }
        public virtual ICollection<SurveyMst> SurveyMsts { get; set; }
        public virtual ICollection<PurchasePackage> PurchasePackages { get; set; }
    }
}
