//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjSurveyPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeMst
    {
        public EmployeeMst()
        {
            this.ClientMsts = new HashSet<ClientMst>();
            this.UserMsts = new HashSet<UserMst>();
            this.PackageMsts = new HashSet<PackageMst>();
        }
    
        public byte EmpID { get; set; }
        public string EmpName { get; set; }
        public bool Gender { get; set; }
        public string EmpAddress { get; set; }
        public string MobileNo { get; set; }
        public string EmailID { get; set; }
        public Nullable<System.DateTime> DtBirth { get; set; }
        public System.DateTime JoiningDate { get; set; }
        public string Designation { get; set; }
        public byte[] Passwd { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> ActiveLeaveDt { get; set; }
        public string EmpImage { get; set; }
        public Nullable<System.DateTime> LastLoginDt { get; set; }
    
        public virtual ICollection<ClientMst> ClientMsts { get; set; }
        public virtual ICollection<UserMst> UserMsts { get; set; }
        public virtual ICollection<PackageMst> PackageMsts { get; set; }
    }
}
