//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjSurveyPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class EwalletMst
    {
        public short SurveyID { get; set; }
        public short UserID { get; set; }
        public Nullable<byte> NoOfAttemptedSurveyQues { get; set; }
        public Nullable<byte> NoOfAttemptedReviewQues { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<short> RewardPoint { get; set; }
    
        public virtual SurveyMst SurveyMst { get; set; }
        public virtual UserMst UserMst { get; set; }
    }
}
