//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjSurveyPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeedbackMst
    {
        public int FeedbackID { get; set; }
        public Nullable<short> SurveyID { get; set; }
        public string FeedbackDisc { get; set; }
        public byte Ratings { get; set; }
        public string UserEmail { get; set; }
        public string UserContactNo { get; set; }
    
        public virtual SurveyMst SurveyMst { get; set; }
    }
}
