//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjSurveyPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageMst
    {
        public PackageMst()
        {
            this.PurchasePackages = new HashSet<PurchasePackage>();
        }
    
        public byte PackageID { get; set; }
        public string PackageTitle { get; set; }
        public string Discription { get; set; }
        public decimal Price { get; set; }
        public byte Duration { get; set; }
        public byte NoOfProduct { get; set; }
        public Nullable<byte> NoOfSurveyQues { get; set; }
        public Nullable<byte> NoOfReviewQues { get; set; }
        public Nullable<short> NoOfResponse { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<byte> EmpID { get; set; }
    
        public virtual EmployeeMst EmployeeMst { get; set; }
        public virtual ICollection<PurchasePackage> PurchasePackages { get; set; }
    }
}
