//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjSurveyPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchasePackage
    {
        public Nullable<byte> PackageID { get; set; }
        public Nullable<short> ClientID { get; set; }
        public short PurchaseID { get; set; }
        public decimal Price { get; set; }
        public Nullable<byte> ProductCnt { get; set; }
        public Nullable<System.DateTime> StartingDate { get; set; }
        public Nullable<System.DateTime> EndingDate { get; set; }
        public Nullable<bool> PaidStatus { get; set; }
        public string RefNo { get; set; }
        public Nullable<System.DateTime> PaidDate { get; set; }
    
        public virtual ClientMst ClientMst { get; set; }
        public virtual PackageMst PackageMst { get; set; }
    }
}
