//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjSurveyPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class QueryMst
    {
        public int QueryID { get; set; }
        public string QueryDisc { get; set; }
        public string EmailID { get; set; }
        public string ReplyDisc { get; set; }
        public Nullable<bool> ReplyStatus { get; set; }
    }
}
