//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjSurveyPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateMst
    {
        public StateMst()
        {
            this.CityMsts = new HashSet<CityMst>();
            this.UserMsts = new HashSet<UserMst>();
        }
    
        public byte StateID { get; set; }
        public string StateName { get; set; }
    
        public virtual ICollection<CityMst> CityMsts { get; set; }
        public virtual ICollection<UserMst> UserMsts { get; set; }
    }
}
