//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjSurveyPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyMst
    {
        public SurveyMst()
        {
            this.FeedbackMsts = new HashSet<FeedbackMst>();
            this.ReviewAns = new HashSet<ReviewAn>();
            this.ReviewQues = new HashSet<ReviewQue>();
            this.SurveyAns = new HashSet<SurveyAn>();
            this.SurveyPayments = new HashSet<SurveyPayment>();
            this.SurveyQues = new HashSet<SurveyQue>();
            this.EwalletMsts = new HashSet<EwalletMst>();
        }
    
        public Nullable<short> ClientID { get; set; }
        public Nullable<short> ProductID { get; set; }
        public short SurveyID { get; set; }
        public Nullable<System.DateTime> SurveyDt { get; set; }
        public Nullable<short> SurveyCnt { get; set; }
        public Nullable<bool> IsPublished { get; set; }
    
        public virtual ClientMst ClientMst { get; set; }
        public virtual ICollection<FeedbackMst> FeedbackMsts { get; set; }
        public virtual ProductMst ProductMst { get; set; }
        public virtual ICollection<ReviewAn> ReviewAns { get; set; }
        public virtual ICollection<ReviewQue> ReviewQues { get; set; }
        public virtual ICollection<SurveyAn> SurveyAns { get; set; }
        public virtual ICollection<SurveyPayment> SurveyPayments { get; set; }
        public virtual ICollection<SurveyQue> SurveyQues { get; set; }
        public virtual ICollection<EwalletMst> EwalletMsts { get; set; }
    }
}
