//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjSurveyPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferAmount
    {
        public Nullable<short> UserID { get; set; }
        public int TAID { get; set; }
        public Nullable<System.DateTime> TADate { get; set; }
        public Nullable<short> TotalTransferRewardPoint { get; set; }
        public Nullable<short> TotalTransferAmount { get; set; }
        public string TransferTo { get; set; }
        public string TransferToUserName { get; set; }
        public string RefNo { get; set; }
    
        public virtual UserMst UserMst { get; set; }
    }
}
