//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjSurveyPro
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMst
    {
        public UserMst()
        {
            this.ReviewAns = new HashSet<ReviewAn>();
            this.SurveyAns = new HashSet<SurveyAn>();
            this.TransferAmounts = new HashSet<TransferAmount>();
            this.EwalletMsts = new HashSet<EwalletMst>();
        }
    
        public short UserID { get; set; }
        public string UserName { get; set; }
        public bool Gender { get; set; }
        public string UserAddress { get; set; }
        public Nullable<byte> CityID { get; set; }
        public Nullable<byte> StateID { get; set; }
        public string MobNo { get; set; }
        public string EmailID { get; set; }
        public Nullable<System.DateTime> DtBirth { get; set; }
        public System.DateTime JoiningDate { get; set; }
        public byte[] Passwd { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> ActiveLeaveDate { get; set; }
        public string UserImage { get; set; }
        public Nullable<System.DateTime> LastLoginDt { get; set; }
        public Nullable<short> RedeemRewardPoint { get; set; }
        public Nullable<byte> ApprovedEmpID { get; set; }
    
        public virtual CityMst CityMst { get; set; }
        public virtual ICollection<ReviewAn> ReviewAns { get; set; }
        public virtual StateMst StateMst { get; set; }
        public virtual ICollection<SurveyAn> SurveyAns { get; set; }
        public virtual ICollection<TransferAmount> TransferAmounts { get; set; }
        public virtual ICollection<EwalletMst> EwalletMsts { get; set; }
        public virtual EmployeeMst EmployeeMst { get; set; }
    }
}
